//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatre_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actors
    {
        public int Actor_id { get; set; }
        public string Name_actor { get; set; }
        public string Surname_actor { get; set; }
        public string Exposition { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Actors Actors1 { get; set; }
        public virtual Actors Actors2 { get; set; }
    }
}
