//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatre_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public Nullable<int> Spectacle_ID { get; set; }
        public Nullable<int> Type_Price { get; set; }
        public Nullable<int> Price { get; set; }
        public int Price_id { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Spectacles Spectacles { get; set; }
    }
}
