//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatre_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spectacles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spectacles()
        {
            this.Prices = new HashSet<Prices>();
        }
    
        public int Spectacle_id { get; set; }
        public string Spectacle_name { get; set; }
        public string Exposition_sp { get; set; }
        public System.DateTime Date_sp { get; set; }
        public int Actor1 { get; set; }
        public int Actor2 { get; set; }
        public int Actor3 { get; set; }
        public int Actor4 { get; set; }
        public int Actor5 { get; set; }
        public int Actor6 { get; set; }
        public int Actor7 { get; set; }
        public int Actor8 { get; set; }
        public int Actor9 { get; set; }
        public int Actor10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prices> Prices { get; set; }
    }
}
