//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theatre_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string Pin { get; set; }
        public string E_mail { get; set; }
        public Nullable<bool> Type { get; set; }
    }
}
